version: '3.8'
services:
  db:
    image: 'postgres:13'
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - mynetwork
    # volumes:
    #   - ./main-app/config/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:6.0
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  main-app:
    # image: main-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    expose:
      - ${SERVER_PORT}
    volumes:
      - ./main-app:/usr/src/app
    depends_on:
      - redis
      - db
    networks:
      - mynetwork
    command: sh -c "npx sequelize-cli db:migrate && npm run db.seed.all && npm start"
    deploy:
      restart_policy:
        condition: on-failure

  front-app:
    # image: front-app
    build:
      context: .
      dockerfile: Dockerfile.fe
    volumes:
      - ./web:/usr/src/app
    ports:
      - ${FRONT_PORT}:${FRONT_PORT}
    # depends_on:
    #   - 'main-app'
    links:
      - 'main-app'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
